name: auto-merge

on:
  pull_request_target:
    types: [ labeled, unlabeled, opened, synchronize, reopened, ready_for_review, review_requested ]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - run: gh pr merge --auto --rebase "$PR_URL"
        env: 
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  auto-approve:
    runs-on: ubuntu-latest
    needs: enable-auto-merge
    steps:
    - uses: hmarr/auto-approve-action@v3
      with: 
        github-token: "${{ secrets.GITHUB_TOKEN }}"
